---
# hosts.yml

# all:
#   hosts:
#     webserver01:
#       ansible_host: 10.1.10.100
#     webserver02:
#       ansible_host: 10.1.10.101
#     dbserver01:
#       ansible_host: 10.1.10.102
#     appserver01:
#       ansible_host: 10.1.10.103

all:
  children:
    webservers:
      hosts:
        webserver01:
          ansible_host: 10.1.10.100
        webserver02:
          ansible_host: 10.1.10.101
      vars:
        web_server_type: nginx  # Example variable for all web servers

    databases:
      hosts:
        dbserver01:
          ansible_host: 10.1.10.102
      vars:
        db_type: mysql  # Example variable for all database servers

    application_servers:
      hosts:
        appserver01:
          ansible_host: 10.1.10.103
      vars:
        app_type: django  # Example variable for all application servers

    special_servers:  # If a server requires special configuration
      hosts:
        dbserver01:  # Example: dbserver01 receives a special configuration
      vars:
        special_config: true
