---
# requirements.yml

roles:
  # Roles from Ansible Galaxy
  - name: geerlingguy.nginx
    version: 3.1.0  # Specific version
  - name: geerlingguy.mysql
    version: 2.0.0

  # Custom role from a GitHub repository
  - name: my_custom_role
    src: git+https://github.com/meinuser/mein_ansible_repo.git
    version: main  # Or a specific branch/tag
    scm: git

  # Role from a private GitHub repository with SSH access
  - name: private_role
    src: git+ssh://git@github.com/meinuser/private_ansible_role.git
    version: develop
    scm: git

collections:
  # Ansible collections from Galaxy
  - name: community.general
    version: 5.3.0
  - name: community.docker
    version: 3.4.0

  # Collection directly from a GitHub repository
  - name: my_custom_collection
    type: git
    source: https://github.com/meinuser/meine_ansible_collection.git
    version: v1.0.0
